# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('room_identifier', models.CharField(db_index=True, max_length=64)),
                ('url', models.CharField(max_length=256)),
                ('street', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(null=True)),
                ('rent', models.IntegerField()),
                ('room_description', models.TextField()),
                ('profile_description', models.TextField()),
                ('mates_description', models.TextField()),
                ('crawled_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
