# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='to_text',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_identifier',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
