# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 19:23
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20170414_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='to_text',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
